### ISSUE TITLE
Make this repo private?

### ISSUE THREAD

**Issue by bechang** [BrianNewsom/PPL#1]
Dear Brian and Ross,

The development effort in the lab projects is significant. So that future 3155 students can get as much out of the lab projects, could you convert this repo into a private one or otherwise take down this publicly available repository?

Thank you for your consideration.

Sincerely,
Bor-Yuh Evan Chang

**Comment by BrianNewsom** [comment]
Professor Chang,

Hope all is well for you!

So sorry for the inconvenience this has caused - it was certainly not an attempt to open our work to others, but rather showcase past programming projects to employers, etc.  

I will delete this repository now.

Thanks,
Brian
